#!/bin/bash
#SBATCH --time=4

# The line SBATCH --time=4 means: max exec time of the batch is 4 minutes
# When developping and debuging: use small test and small time limits
# After you can sublit Batch with 15, 30, 60, 120 minutes

source /etc/profile

module load py-mpi4py/3.1.4/gcc-12.3.0-openmpi
module load valgrind/3.20.0/gcc-12.3.0-openmpi
#module load ... others modules to load

# go in the right directory (where is the pgm to execute)
cd ~/HPC_Project


echo "========== MPI LAUNCHER for iso3d to use with sbatch =========="

# Command to execute
# ex : 8 processes distributed on 2 nodes: 2 per socket (i.e. 4 per node)

#@param -n = -np number process 
#@param -u = -u user number 
#@param -m = -m method
#@param -f = -d debug option 
numberProcess=-1
user=-1
method=""
iter=50
ants=50
delta=0.1
rho=0.1


show_help() {
python3 ACO-mpi-scatter.py -h
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

while getopts 'n:u:m:i:a:d:r' flag; do
    case "${flag}" in
        n) numberProcess="${OPTARG}" ;;
        u) user="${OPTARG}" ;;
        m) method="${OPTARG}" ;;
        i) iter="${OPTARG}" ;;
        a) ants="${OPTARG}" ;;
        d) delta="${OPTARG}" ;;
        r) rho="${OPTARG}" ;;
    esac
done
if ! [[ "$numberProcess" =~ ^[1-8]+$ ]]; then
    echo "Error: Argument numberProcess is not between 1 and 8"
    exit 128
fi
if ! [[ "$user" =~ ^[1-9]+$ ]]; then
    echo "Error: Argument user is not a number from 1-9"
    exit 128
fi
if [[ "$method" != "linear" && "$method" != "quadratic" && "$method" != "relu"  && "$method" != "performance" ]]; then
    echo "Error: Argument method must be one of linear, quadratic, relu or performance."
    exit 128
fi
if ! [[ "$iter" =~ ^[0-9]+$ ]]; then
    echo "Error: Argument iter is not a number"
    exit 128
fi
if ! [[ "$ants" =~ ^[0-9]+$ ]]; then
    echo "Error: Argument ants is not a number"
    exit 128
fi
if ! [[ "$delta" =~ ^[0-9]+[.][0-9]+$ ]]; then
    echo "Error: Argument delta is not a float"
    exit 128
fi
if ! [[ "$rho" =~ ^[0-9]+[.][0-9]+$ ]]; then
    echo "Error: Argument rho is not a float"
    exit 128
fi

echo "===================== MPIRUN ======================="
/usr/bin/mpirun -np $numberProcess -map-by ppr:1:node:PE=16 -rank-by core python3 ACO-mpi-scatter.py --user $user --method $method --iter $iter --numberOfAnt $ants --delta $delta --rho $rho  --cachegrind
echo "===================== END ======================="

